joint_names: [head_1_joint,head_2_joint,head_3_joint]
module_ids: [70,71,72]
motor_direction: [1,1,1]

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 68

devices: ["/dev/pcan1","/dev/pcan1","/dev/pcan1"]

