joint_names: [sensorring_joint]
module_ids: [73]
motor_direction: [1]

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 68

devices: ["/dev/pcan1"]

