joint_names: [torso_1_joint,torso_2_joint,torso_3_joint]
module_ids: [30,31,32]
motor_direction: [1,1,1]

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 68

devices: ["/dev/pcan0","/dev/pcan0","/dev/pcan0"]

